const chrome={zh:{brandMeta:'即构',navWork:'作品',navServices:'服务',navStudio:'工作室',navContact:'联系',footerMeta:'即构',footerLine:'大学生 AI 与软件支持工作室',footerBottom:'Made with care, in public.',backTop:'回到顶部 ↑',styleLabel:'风格',stylePanelTitle:'选择主页风格',styleUnrushed:'黑白工作室 · 彩色作品',styleOrigin:'产品工作室 · 价格透明',styleSkeg:'独立开发者 · 编辑感',styleGoodTech:'AI-first · 快速上线',styleUnitar:'实验室 · 黑客感',styleSodium:'产品目录 · 工具优先',styleSnowFox:'AI agency · 强视觉',styleMarket:'Product studio · 企业感',styleHermes:'蓝白宣言 · 项目路径'},en:{brandMeta:'JIGOU',navWork:'Work',navServices:'Services',navStudio:'Studio',navContact:'Contact',footerMeta:'JIGOU',footerLine:'AI & software support for university students',footerBottom:'Made with care, in public.',backTop:'Back to top ↑',styleLabel:'Style',stylePanelTitle:'Choose a homepage style',styleUnrushed:'Monochrome studio · colour in the work',styleOrigin:'Product studio · clear pricing',styleSkeg:'Independent software · editorial',styleGoodTech:'AI-first · launch fast',styleUnitar:'Lab system · hacker energy',styleSodium:'Product catalogue · tools first',styleSnowFox:'AI agency · bold visual energy',styleMarket:'Product studio · enterprise polish',styleHermes:'Blue statement · project paths'}};
const pageCopy={
unrushed:{zh:{eyebrow:'独立软件工作室 / 2026',title:'想法进来。<br><em>产品出去。</em>',lede:'网站、AI 工具、课程项目和数据处理，都可以交给 Z Lab。',primary:'提交需求',secondary:'查看作品',palette:'作品就是调色板',workTitle:'把事情想清楚，<br><em>再把它做好。</em>',workNote:'每个项目先解决一个明确的问题，确定做法后再开始写代码。',cases:[['CourseKit','从想法到可以提交的课程项目。','结构梳理、页面搭建、报告与演示材料，一次完成。'],['PromptPad','用 AI 少做一些重复工作。','轻量 Agent、自动化脚本、个人知识库和工作流。'],['DataFit','把数据整理好，结果也会更清楚。','清洗、拟合、可视化和实验报告，让结果可以解释。'],['Deploy','环境装好，项目就能继续。','GPT、Codex、Python 与开发环境的安装和排错。']],servicesTitle:'从一个需求，<br><em>做出第一版。</em>',servicesNote:'先聊清楚要做什么，再确定范围、价格和交付内容。',services:[['01','AI 账号与开发环境','¥29+'],['02','课程作业与项目','¥59+'],['03','AI 工具与小型应用','¥129+'],['04','定制与校园合作','面议']],studioTitle:'先做重要的，<br><em>再慢慢完善。</em>',studioNote:'Z Lab 帮大学生做 AI 和软件项目。你把需求发来，我们一起定下做法。',principles:[['说清需求','就算现在只有一句“老师让我做个网站”，也可以从这里开始。'],['控制范围','先做最需要的部分，页面能打开、项目能演示，再逐步补充。'],['交付明白','开始前写清楚做什么、什么时候交付，以及最后会收到什么。']],contactTitle:'有一个想法？<br><em>先发给我们。</em>',contactNote:'把想做的内容、截止时间和预算发来。我们看过之后，回复你能做哪些、需要多少时间。'},en:{eyebrow:'Independent software studio / since 2026',title:'Ideas in.<br><em>Products out.</em>',lede:'Websites, AI tools, coursework and data work, made into something you can use.',primary:'Start a project',secondary:'See the work',palette:'The palette is the work',workTitle:'Small, clear,<br><em>ready to ship.</em>',workNote:'One clear problem per project. We agree on the approach, then write the code.',cases:[['CourseKit','From rough brief to a project you can submit.','Structure, pages, reports and presentation materials, in one focused build.'],['PromptPad','AI that does useful work.','Lightweight agents, automations, personal knowledge bases and workflows.'],['DataFit','Data work without getting stuck at step one.','Cleaning, fitting, visualisation and reports that make the result explainable.'],['Deploy','Get the setup right. Start the project.','GPT, Codex, Python and development environment setup and fixes.']],servicesTitle:'Start with one need,<br><em>then make it real.</em>',servicesNote:'We agree on the scope first, then set the deliverables and price.',services:[['01','AI accounts & dev setup','¥29+'],['02','Coursework & student projects','¥59+'],['03','AI tools & small apps','¥129+'],['04','Custom & campus work','Scoped']],studioTitle:'Focus on the work,<br><em>then improve it.</em>',studioNote:'Z Lab is an independent software studio for university students. Clear language, useful results.',principles:[['Speak plainly','Start with “my professor asked me to build a website.” You do not need product language first.'],['Keep it small','Make the important part work, open, demo-ready and shippable before expanding.'],['Deliver clearly','Every project says what gets made, when it arrives and what you will receive.']],contactTitle:'Have an idea?<br><em>Send it over.</em>',contactNote:'Tell us what you want to make, your deadline and your budget range. We will tell you what is possible and what it would take.'}},
origin:{zh:{kicker:'Z LAB / PRODUCT STUDIO',title:'把想法做成<br><span>能上线的产品。</span>',lede:'网站、AI 应用和校园项目，从第一版做到交付。',button:'开始一个项目',briefTitle:'先从第一步开始',briefText:'把需求列清楚，按计划完成。',briefItems:['需求梳理','设计与开发','部署与交接'],sectionTitle:'我们能帮你<br><span>做什么</span>',services:[['01','网站与落地页','让别人看得懂，也愿意打开。'],['02','AI 工具与自动化','把重复的步骤交给脚本。'],['03','课程与校园项目','报告、数据和演示页面，一起整理好。']],proofTitle:'先把眼前的事<br>做好。',proofs:[['4+','项目类型'],['7 days','最快开始'],['1','位对接人']],pricingTitle:'直接看起步价',pricing:[['Setup','AI 账号与环境','¥29+'],['Build','课程项目与网站','¥59+'],['Ship','AI 工具与小型应用','¥129+']],contactTitle:'想开始了？<br><span>那就发来吧。</span>',contactNote:'告诉我们要做什么、什么时候要、预算大概多少。'},en:{kicker:'Z LAB / PRODUCT STUDIO',title:'Turn the idea into<br><span>something that ships.</span>',lede:'Websites, AI applications and campus projects, from first version to handoff.',button:'Start a project',briefTitle:'Start with the brief',briefText:'Set the brief, then build to it.',briefItems:['Scope the brief','Design & build','Deploy & hand off'],sectionTitle:'What we can<br><span>build for you</span>',services:[['01','Websites & landing pages','Make the project visible, usable and clear.'],['02','AI tools & automation','Turn repetitive work into one simple flow.'],['03','Coursework & campus builds','From reports and data to a demo-ready result.']],proofTitle:'No bloated proposal,<br>just the next step.',proofs:[['4+','delivery tracks'],['7 days','fastest start'],['1','direct contact']],pricingTitle:'Simple starting prices',pricing:[['Setup','AI accounts & environment','¥29+'],['Build','Coursework & websites','¥59+'],['Ship','AI tools & small apps','¥129+']],contactTitle:'Ready to<br><span>start?</span>',contactNote:'Tell us what you want, when you need it and the budget range.'}},
skeg:{zh:{label:'INDEPENDENT SOFTWARE / Z LAB',title:'软件要解决<br><em>手头的问题。</em>',intro:'我们做课程项目、AI 工具、数据应用和网页。范围不用铺得很大，先把眼前的事做完。',cases:[['01','CourseKit','课程项目工具','把复杂作业整理成页面、报告和演示材料。'],['02','PromptPad','AI 工作流','把常用提示词整理起来，少做几遍重复操作。'],['03','DataFit','数据实验','数据清洗、拟合、图表和报告，放在一套流程里做。'],['04','Deploy','开发环境','把环境装好，接着就能写代码。']],noteTitle:'做项目时，我们看三件事',notes:[['范围小一点','每个工具先盯住一件事。'],['节奏快一点','少走不必要的弯路。'],['进度清楚点','项目进度随时可见。']],contactTitle:'有项目要做？',contactText:'把需求写几句发来，我们看过就回复。',contact:'zavierli888@gmail.com'},en:{label:'INDEPENDENT SOFTWARE / Z LAB',title:'Software that<br><em>keeps you on course.</em>',intro:'Focused builds for coursework, AI tools, data work and websites that need finishing.',cases:[['01','CourseKit','Coursework tools','Turn a complicated assignment into clear pages and deliverables.'],['02','PromptPad','AI workflows','Start with one prompt, then turn repeated steps into a workflow.'],['03','DataFit','Data experiments','Cleaning, fitting, charts and reports, together.'],['04','Deploy','Developer setup','Go from “it will not install” to ready to code.']],noteTitle:'Three things matter',notes:[['Smaller','Each product solves one problem.'],['Faster','Do not spend time on ceremony.'],['Clearer','You always know where the project is.']],contactTitle:'Have a project?',contactText:'Send a paragraph. We will tell you if we can help.',contact:'zavierli888@gmail.com'}},
good:{zh:{eyebrow:'AI-FIRST PRODUCT STUDIO',title:'从空白页面<br><em>到上线。</em>',lede:'设计、开发、自动化。先做出第一版，再根据使用情况调整。',button:'启动项目',ticker:'设计 / 构建 / 上线 / 迭代 / 设计 / 构建 / 上线',steps:[['01','DESIGN','先确定要解决的问题','先确定使用对象和要解决的问题，再定第一版。'],['02','BUILD','先做最重要的功能','页面、数据、AI 功能和说明材料一起完成。'],['03','SHIP','上线后交给你使用','完成部署和演示，确认没问题后交付。']],proofs:[['01','从想法开始'],['02','直接协作'],['03','快速交付']],cta:'不用等所有条件都齐了，先做第一版。'},en:{eyebrow:'AI-FIRST PRODUCT STUDIO',title:'From a blank page<br><em>to something live.</em>',lede:'Design, build and automate. Make a first version you can test, show and use.',button:'Start building',ticker:'DESIGN / BUILD / SHIP / ITERATE / DESIGN / BUILD / SHIP',steps:[['01','DESIGN','Clarify the problem','Define who it is for, what it needs to do and what to build first.'],['02','BUILD','Make the core real','Pages, data, AI logic and handoff materials, together.'],['03','SHIP','Put it in the world','Deploy it, demo it, hand it over, then keep improving.']],proofs:[['01','Start with an idea'],['02','Work directly'],['03','Ship quickly']],cta:'Start before everything is perfect.'}},
unitar:{zh:{prompt:'ZLAB / LAB MODE',title:'做点<br><em>有用的小软件。</em>',status:'SYSTEM ONLINE',intro:'这里做 AI、数据、网页和校园工具。先做一版，边用边改。',modules:[['AI','Agent 原型','把想法做成能运行的原型。'],['DATA','实验数据','把原始表格整理成看得懂的结果。'],['WEB','交互页面','让项目不只停留在报告里。'],['SETUP','环境部署','把工具和代码装到你的电脑上。']],logTitle:'BUILD LOG',logs:['brief received','scope reduced','first screen shipped','demo link generated'],command:'zlab run --from idea --to usable',cta:'进入实验室'},en:{prompt:'ZLAB / LAB MODE',title:'Build something<br><em>you have not seen before.</em>',status:'SYSTEM ONLINE',intro:'Think of Z Lab as a small lab: AI, data, web and campus tools. Build first, explain later.',modules:[['AI','Agent prototypes','Turn the idea into a working prototype.'],['DATA','Data experiments','Turn raw tables into a result you can explain.'],['WEB','Interactive pages','Let the project live outside the report.'],['SETUP','Environment setup','Make the tools and code work on your machine.']],logTitle:'BUILD LOG',logs:['brief received','scope reduced','first screen shipped','demo link generated'],command:'zlab run --from idea --to usable',cta:'Enter the lab'}},
sodium:{zh:{eyebrow:'Z LAB / SMALL TOOLS',title:'我们需要的工具，<br><em>自己做出来。</em>',lede:'一组拿来就能用的小工具。',products:[['01','CourseKit','课程项目助手','结构、页面、演示，一起完成。'],['02','PromptPad','AI 提示词工作台','把常用提示词整理成顺手的流程。'],['03','DataFit','数据处理工具','把表格、图表和结论放在一起。'],['04','Deploy','开发环境工具','少折腾配置，早点开始。'],['05','CampusOS','校园小系统','把校园里的小事做成工具。']],statement:'做出来，才知道好不好用。',cta:'有工具想做？'},en:{eyebrow:'Z LAB / SMALL TOOLS',title:'Build the tools<br><em>we wished existed.</em>',lede:'A catalogue of simple, focused tools, ready to use.',products:[['01','CourseKit','Coursework companion','Structure, pages and demos in one place.'],['02','PromptPad','AI prompt workbench','Turn useful prompts into repeatable workflows.'],['03','DataFit','Data utility','Keep sheets, charts and conclusions together.'],['04','Deploy','Dev setup utility','Spend less time configuring, more time building.'],['05','CampusOS','Campus tools','Turn small student problems into useful software.']],statement:'The product is the introduction.',cta:'Have a tool in mind?'}},
snow:{zh:{eyebrow:'SNOW FOX / AI PRODUCT DESIGN',title:'把复杂的技术，<br><em>做得好看，也好用。</em>',lede:'品牌、产品、AI 和交互，做成让人愿意用下去的体验。',button:'聊聊你的想法',capabilities:['Brand systems','AI & agents','Product design','Web experiences'],cases:[['01','AI Studio','从一个模型，做成一套体验。'],['02','Campus Copilot','给校园服务换个好用的入口。'],['03','Data Playground','把数据做成可以点击、可以探索的界面。'],['04','Launch Kit','从命名到页面，一起做完并上线。']],process:['Discover','Shape','Build','Release'],cta:'Make it feel alive.'},en:{eyebrow:'SNOW FOX / AI PRODUCT DESIGN',title:'Make complex tech<br><em>feel fun to use.</em>',lede:'Brand, product, AI and interaction, shaped into digital experiences people want to use.',button:'Talk about an idea',capabilities:['Brand systems','AI & agents','Product design','Web experiences'],cases:[['01','AI Studio','From one model to a complete experience.'],['02','Campus Copilot','A better front door for campus services.'],['03','Data Playground','Turn data into something you can explore.'],['04','Launch Kit','From name to live page, in one launch.']],process:['Discover','Shape','Build','Release'],cta:'Make it feel alive.'}},
market:{zh:{eyebrow:"MARKET / DIGITAL PRODUCT STUDIO",title:"设计、构建，<br><em>让产品往前走。</em>",lede:"帮学生团队、校园组织和早期项目做产品设计与开发。",metrics:[["12","项目方向"],["03","核心能力"],["01","直接对接"]],capabilities:[["Product design","把需求理清楚，做成用户看得懂的页面。"],["Engineering","按项目阶段选合适的技术，先把版本做出来。"],["AI & automation","把 AI 和自动化放进日常工作。"]],engage:[["01","Align","确定要解决的问题、目标和范围。"],["02","Build","分阶段推进，每次交付一部分。"],["03","Grow","根据反馈继续调整。"]],ctaTitle:"准备把产品往前推一步？",ctaText:"把想法发来，我们一起定下一步。"},en:{eyebrow:"MARKET / DIGITAL PRODUCT STUDIO",title:"Design, build,<br><em>and move the product forward.</em>",lede:"Clear product design and engineering support for student teams, campus organisations and early-stage ideas.",metrics:[["12","project tracks"],["03","core capabilities"],["01","direct contact"]],capabilities:[["Product design","Turn complex needs into something people understand."],["Engineering","Build with the right technology for the stage."],["AI & automation","Put intelligence into a workflow that actually helps."]],engage:[["01","Align","Set the problem, goal and scope."],["02","Build","Ship something visible in short cycles."],["03","Grow","Use feedback to improve and expand."]],ctaTitle:"Ready to move the product forward?",ctaText:"Send the idea. We will find the next step together."}}
};
const styleNames={unrushed:'Unrushed',origin:'Origin',skeg:'Skeg','good-tech':'Good Tech',unitar:'UNITAR',sodium:'Sodium','snow-fox':'Snow Fox',market:'Market',hermes:'Hermes'};
const styleKey={unrushed:'unrushed',origin:'origin',skeg:'skeg','good-tech':'good',unitar:'unitar',sodium:'sodium','snow-fox':'snow',market:'market',hermes:'hermes'};

pageCopy.hermes={
 zh:{
  kicker:'Z LAB / 大学生 AI 与软件工作室',
  heroTitle:'从想法<br><em>到可用的一版。</em>',
  heroText:'网站、AI 工具、课程项目和数据任务。带上手头的材料，我们一起把下一步做出来。',
  primary:'发来你的想法',secondary:'探索项目方向',heroIndex:'IDEAS / BUILT TO USE',heroOrbit:'FROM IDEA TO VERSION',
  briefEyebrow:'开始合作 / 一封邮件',briefTitle:'告诉我们三件事。',
  briefItems:[['01','你的目标','想解决什么问题'],['02','已有材料','资料、链接或半成品'],['03','时间节点','希望何时用上']],briefCta:'写邮件开始',
  workEyebrow:'PROJECT PATHS',workTitle:'从你现在的位置开始。',workIntro:'每个项目的起点都不同。先看清要解决的问题，再决定第一版做多大。',
  paths:[['01','一个想法','把想法整理成能展示、能讨论的页面或原型。','IDEA → PROTOTYPE'],['02','一份作业','把资料、数据和表达组织成清楚的交付物。','MATERIAL → OUTPUT'],['03','一个卡点','排查工具、环境或现有项目里阻碍进度的问题。','BLOCKER → NEXT STEP']],
  servicesEyebrow:'CAPABILITIES',servicesTitle:'需要什么，<br><em>就解决什么。</em>',servicesIntro:'能力围绕具体任务组合，不要求你先选好技术方案。',
  services:[['AI / TOOLS','AI 工具与流程','配置并用好 GPT、Codex 与其他 AI 工具。'],['WEB / PRODUCT','网站与页面','为项目制作介绍页、界面或可用的第一版。'],['COURSE / MAKING','课程项目','把课程想法做成报告、网页或展示材料。'],['DATA / VISUAL','数据与图表','整理数据，做出清楚、可复查的图表。'],['SETUP / DEBUG','软件与环境','处理安装、配置、部署与排错。'],['AUTOMATION','重复任务自动化','把适合自动化的步骤连接成简单流程。']],
  studioEyebrow:'HOW WE WORK',studioTitle:'一边做，<br><em>一边看清楚。</em>',studioIntro:'把下一步缩小到能交付、能验证的范围。',
  steps:[['01','讲清目标','先确认谁会使用、要解决什么，以及手上已经有什么。'],['02','做出一版','围绕最重要的任务，交付可以查看或使用的结果。'],['03','根据反馈调整','一起检查实际使用中的问题，再决定是否继续扩展。']],
  faqEyebrow:'BEFORE WE START',faqTitle:'常见的两个问题。',faqs:[['需要准备完整需求吗？','不需要。先发目标、已有材料和时间节点，我们可以一起明确范围。'],['可以从一个小问题开始吗？','可以。工具配置、页面调整、数据处理或项目中的具体卡点，都适合作为起点。']],
  contactEyebrow:'YOUR NEXT MOVE',contactTitle:'下一版，<br><em>从这里开始。</em>',contactIntro:'写下你要做的事，我们会从目标和可行的第一步聊起。',contactCta:'联系 Z Lab',mailSubject:'Z Lab 项目咨询',mailBody:'你好，Z Lab！\n\n我想完成：\n\n我现在已有：\n\n希望使用的时间：\n'
 },
 en:{
  kicker:'Z LAB / AI & SOFTWARE FOR STUDENTS',
  heroTitle:'From idea<br><em>to a working version.</em>',
  heroText:'Websites, AI tools, coursework and data projects. Bring what you have; we will shape the next useful step together.',
  primary:'Send your idea',secondary:'Explore project paths',heroIndex:'IDEAS / BUILT TO USE',heroOrbit:'FROM IDEA TO VERSION',
  briefEyebrow:'START HERE / ONE EMAIL',briefTitle:'Tell us three things.',
  briefItems:[['01','Your goal','What needs to work'],['02','What you have','Notes, links or a draft'],['03','Your timeline','When you need it']],briefCta:'Write the first email',
  workEyebrow:'PROJECT PATHS',workTitle:'Start where you are.',workIntro:'Every project starts somewhere different. We clarify the problem first, then decide what a useful first version needs.',
  paths:[['01','An idea','Turn a thought into a page or prototype people can see and discuss.','IDEA → PROTOTYPE'],['02','An assignment','Shape research, data and explanation into a clear deliverable.','MATERIAL → OUTPUT'],['03','A blocker','Work through a tool, setup or project issue that is slowing you down.','BLOCKER → NEXT STEP']],
  servicesEyebrow:'CAPABILITIES',servicesTitle:'Solve the task<br><em>in front of you.</em>',servicesIntro:'We combine the skills the task needs. You do not need to choose a technology first.',
  services:[['AI / TOOLS','AI tools and workflows','Set up and use GPT, Codex and other AI tools well.'],['WEB / PRODUCT','Websites and pages','Build a project page, interface or useful first version.'],['COURSE / MAKING','Course projects','Turn a course idea into a report, website or presentation.'],['DATA / VISUAL','Data and charts','Organize data into clear, checkable visuals.'],['SETUP / DEBUG','Software and setup','Handle installation, configuration, deployment and debugging.'],['AUTOMATION','Task automation','Connect repetitive steps into a simpler workflow.']],
  studioEyebrow:'HOW WE WORK',studioTitle:'Build, check,<br><em>then improve.</em>',studioIntro:'Make the next step small enough to deliver and verify.',
  steps:[['01','Define the goal','Identify who will use it, what they need and what already exists.'],['02','Build a version','Deliver something people can inspect or use around the key task.'],['03','Use feedback','Check what happens in use, then decide whether to expand.']],
  faqEyebrow:'BEFORE WE START',faqTitle:'Two common questions.',faqs:[['Do I need a complete brief?','No. Send your goal, the materials you already have and your timeline. We can clarify the scope together.'],['Can we start with a small problem?','Yes. Tool setup, page changes, data work or one project blocker are all good starting points.']],
  contactEyebrow:'YOUR NEXT MOVE',contactTitle:'The next version<br><em>starts here.</em>',contactIntro:'Tell us what you want to make. We will start with the goal and a practical first step.',contactCta:'Contact Z Lab',mailSubject:'Z Lab project inquiry',mailBody:'Hello Z Lab,\n\nI want to make:\n\nI already have:\n\nI need it by:\n'
 }
};

const posterCopy={
zh:{kicker:'面向大学生的 AI 与软件工作室',title:'Z Lab',originTitle:'做点有用的。',skegTitle:'做给<br><em>学生的</em><br>软件。',goodTitle:'把事<br><em>做成。</em>',sodiumTitle:'小工具。<br><em>帮你把事做完。</em>',snowTitle:'让它<br><em>好用。</em>',marketTitle:'把下一步<br><em>做出来。</em>',studentsTitle:'面向<br>大学生',tools:'GPT、Codex、网页、数据。',sub:'面向大学生，帮你处理课程、创作和开发中的具体问题。',contact:'zavierli888@gmail.com',services:[['01','AI 工具与账号','GPT、Codex、Plus'],['02','课程项目与数据','报告、网页、图表'],['03','软件与环境支持','安装、部署、排错']]},
en:{kicker:'AI & software studio for university students',title:'Z Lab',originTitle:'Make something useful.',skegTitle:'Software<br><em>for students.</em>',goodTitle:'MAKE<br><em>IT</em><br>WORK.',sodiumTitle:'Small tools.<br><em>Useful days.</em>',snowTitle:'Make it<br><em>click.</em>',marketTitle:'Design<br><em>the next</em><br>step.',studentsTitle:'UNIVERSITY<br>STUDENTS',tools:'GPT, Codex, web, data.',sub:'For university students, help with coursework, creative projects and everyday development.',contact:'zavierli888@gmail.com',services:[['01','AI tools & accounts','GPT, Codex, Plus'],['02','Coursework & data','Reports, web, charts'],['03','Software & setup','Install, deploy, fix']]}
};
function posterMarkup(kind){
 const p=posterCopy[lang], mailto='mailto:'+p.contact, item=(x,i)=>'<div class="poster-service poster-service-'+i+'"><b>'+x[0]+'</b><strong>'+x[1]+'</strong><span>'+x[2]+'</span></div>', services=p.services.map(item).join('');
 if(kind==='unrushed') return '<section class="poster poster-unrushed"><div class="poster-top"><b>Z LAB</b></div><div class="poster-unrushed-main"><div class="poster-z">Z</div><div class="poster-unrushed-copy"><h1>'+p.title+'</h1><h2>'+p.sub+'</h2><a href="'+mailto+'">'+p.contact+' ↗</a></div></div><div class="poster-unrushed-colorline"><i></i><i></i><i></i><i></i></div></section>';
 if(kind==='origin') return '<section class="poster poster-origin"><div class="poster-origin-grid-bg"></div><div class="poster-origin-tools"><span>↻</span><b>+</b></div><div class="poster-origin-top"><b>ORIGIN / Z LAB</b></div><div class="poster-origin-grid"><div><h1>'+p.title+'<br><em>'+p.originTitle+'</em></h1><p>'+p.sub+'</p><a href="'+mailto+'">'+p.contact+' ↗</a></div><div class="poster-origin-visual"><div class="poster-origin-visual-mark">+</div><i></i><b></b></div></div></section>';
 if(kind==='skeg') return '<section class="poster poster-skeg"><div class="poster-skeg-head"><b>SKEG / Z LAB</b></div><div class="poster-skeg-grid"><div class="poster-skeg-copy"><h1>'+p.skegTitle+'</h1><p>'+p.sub+'</p><a href="'+mailto+'">'+p.contact+' ↗</a></div><div class="poster-skeg-spec"><div class="poster-skeg-drawing"><i></i><b></b></div><div class="poster-skeg-meta"><span>INDEPENDENT</span><span>CUSTOM BUILT</span><span>STEADY</span></div></div></div></section>';
 if(kind==='good-tech') return '<section class="poster poster-good"><div class="poster-good-top"><b>Z LAB</b></div><div class="poster-good-grid"><div class="poster-good-title"><h1>'+p.goodTitle+'</h1><p>'+p.sub+'</p></div><div class="poster-good-console">'+services+'<a href="'+mailto+'">START → '+p.contact+'</a></div></div><div class="poster-good-ticker">AI TOOLS // COURSEWORK // SOFTWARE SUPPORT // AI TOOLS // COURSEWORK // SOFTWARE SUPPORT</div></section>';
 if(kind==='unitar') return '<section class="poster poster-unitar"><div class="poster-unitar-head"><b>0xZLAB</b></div><div class="poster-unitar-grid"><div class="poster-unitar-command"><h1>Z Lab<span>_</span></h1><p>'+p.sub+'</p><h2>'+p.tools+'</h2></div><div class="poster-unitar-categories"><span>AI</span><span>LOCAL</span><span>AV</span><span>WEB</span><a href="'+mailto+'">$ start_project ↗</a></div></div><div class="poster-unitar-foot"><b>'+p.contact+'</b></div></section>';
 if(kind==='sodium') return '<section class="poster poster-sodium"><div class="poster-sodium-head"><span>THE Z LAB CATALOGUE</span></div><div class="poster-sodium-grid"><div class="poster-sodium-number">03</div><div class="poster-sodium-title"><h1>'+p.sodiumTitle+'</h1><span>'+p.sub+'</span><a href="'+mailto+'">'+p.contact+' ↗</a></div></div><div class="poster-sodium-products">'+p.services.map((x,i)=>'<div class="sodium-tile tile-'+i+'"><b>'+x[0]+'</b><strong>'+x[1]+'</strong><span>'+x[2]+'</span><i>'+(i+1)+'</i></div>').join('')+'</div></section>';
 if(kind==='snow') return '<section class="poster poster-snow"><div class="poster-snow-top"><b>Z LAB</b></div><div class="poster-snow-ribbon"><span>AI</span><span>DESIGN</span><span>AGENTS</span><span>3D</span><span>AI</span><span>DESIGN</span><span>AGENTS</span><span>3D</span></div><div class="poster-snow-grid"><div class="poster-snow-copy"><h1>'+p.snowTitle+'</h1><p>'+p.sub+'</p><a href="'+mailto+'">'+p.contact+' ↗</a></div><div class="poster-snow-orbit"><div class="snow-orbit-core">Z</div><i class="snow-orbit-ring ring-a"></i><i class="snow-orbit-ring ring-b"></i></div></div><div class="poster-snow-services">'+p.services.map((x,i)=>'<a href="'+mailto+'"><small>'+x[0]+'</small><b>'+x[1]+'</b><span>'+x[2]+'</span><i>↗</i></a>').join('')+'</div></section>';
 return '<section class="poster poster-market"><div class="poster-market-grid"><div class="poster-market-title"><h1>'+p.marketTitle+'</h1><p>'+p.sub+'</p><a href="'+mailto+'">'+p.contact+' ↗</a></div><div class="poster-market-visual"><div class="poster-market-visual-orb"></div><span>PRODUCT<br>STUDIO</span></div><aside><b>'+p.studentsTitle+'</b></aside></div></section>';
}

const root=document.documentElement,main=document.querySelector('#top'),langToggle=document.querySelector('#langToggle'),themeToggle=document.querySelector('#themeToggle'),styleToggle=document.querySelector('#styleToggle'),stylePanel=document.querySelector('#stylePanel'),styleCurrent=document.querySelector('#styleCurrent'),styleOptions=[...document.querySelectorAll('.style-option')];
let lang=localStorage.getItem('zlab-lang')||'zh';
let style=localStorage.getItem('zlab-style')||'hermes';
if(!localStorage.getItem('zlab-hermes-default-v1')){
 if(style==='unrushed')style='hermes';
 localStorage.setItem('zlab-hermes-default-v1','1');
}
const mail='zavierli888@gmail.com';
function renderChrome(){const dict=chrome[lang];document.querySelectorAll('[data-i18n]').forEach(el=>{const value=dict[el.dataset.i18n];if(value!==undefined)el.innerHTML=value});document.documentElement.lang=lang==='zh'?'zh-CN':'en';langToggle.textContent=lang==='zh'?'中 / EN':'EN / 中';localStorage.setItem('zlab-lang',lang)}
function esc(value){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function link(text){return '<a class="variant-button" href="mailto:'+mail+'?subject=Z%20Lab%20Project"><span>'+text+'</span><span aria-hidden="true">↗</span></a>'}
function unrushed(c){return '<div class="variant-page page-unrushed">'+posterMarkup('unrushed')+'<section class="unrushed-work variant-pad" id="work"><div class="variant-section-head"><p>/ THE WORK</p><h2>'+c.workTitle+'</h2><span>'+c.workNote+'</span></div><div class="unrushed-grid">'+c.cases.map((x,i)=>'<a class="unrushed-case case-'+i+'" href="#contact"><div class="case-art"><small>0'+(i+1)+' / '+['WEB','AI','DATA','SETUP'][i]+'</small><strong>'+x[0]+'</strong><em>↗</em></div><h3>'+x[1]+'</h3><p>'+x[2]+'</p></a>').join('')+'</div></section><section class="unrushed-services variant-pad" id="services"><div class="variant-section-head"><p>/ SERVICES</p><h2>'+c.servicesTitle+'</h2><span>'+c.servicesNote+'</span></div><div class="unrushed-service-list">'+c.services.map(x=>'<div><small>'+x[0]+'</small><strong>'+x[1]+'</strong><b>'+x[2]+'</b><em>↗</em></div>').join('')+'</div></section><section class="unrushed-studio variant-pad" id="studio"><div class="variant-section-head"><p>/ THE STUDIO</p><h2>'+c.studioTitle+'</h2><span>'+c.studioNote+'</span></div><div class="unrushed-principles">'+c.principles.map((x,i)=>'<article><small>0'+(i+1)+'</small><h3>'+x[0]+'</h3><p>'+x[1]+'</p></article>').join('')+'</div></section><section class="unrushed-contact variant-pad" id="contact"><div><p class="variant-eyebrow">/ START SOMETHING</p><h2>'+c.contactTitle+'</h2><p>'+c.contactNote+'</p>'+link(mail)+'</div><code>$ zlab start<br /><b>your idea</b><br /><i>→ accepted</i></code></section></div>'}
function origin(c){return '<div class="variant-page page-origin origin-v2">'+posterMarkup('origin')+'<div class="origin-pulse"><span>WEBSITE</span><span>AI TOOL</span><span>COURSEWORK</span><span>DATA</span><span>WEBSITE</span><span>AI TOOL</span></div><section class="origin-rail variant-pad" id="services"><aside><small>02 / OFFER</small><h2>'+c.sectionTitle+'</h2><p>'+c.briefText+'</p></aside><div class="origin-rail-list">'+c.services.map(function(x,i){return '<article><span>'+x[0]+'</span><div><h3>'+x[1]+'</h3><p>'+x[2]+'</p></div><b>0'+(i+1)+'</b></article>'}).join('')+'</div></section><section class="origin-ledger variant-pad" id="work"><div class="origin-ledger-head"><small>03 / PROOF</small><h2>'+c.proofTitle+'</h2></div><div class="origin-ledger-numbers">'+c.proofs.map(function(x){return '<div><strong>'+x[0]+'</strong><span>'+x[1]+'</span></div>'}).join('')+'</div></section><section class="origin-price-strip variant-pad"><small>04 / STARTING POINT</small><div>'+c.pricing.map(function(x){return '<span><b>'+x[0]+'</b> '+x[1]+' <strong>'+x[2]+'</strong></span>'}).join('')+'</div></section><section class="origin-cta origin-cta-v2 variant-pad" id="contact"><p>05 / START PROJECT</p><h2>'+c.contactTitle+'</h2><span>'+c.contactNote+'</span>'+link(c.button)+'</section></div>'}
function skeg(c){return '<div class="variant-page page-skeg">'+posterMarkup('skeg')+'<section class="skeg-cases variant-pad" id="work"><div class="skeg-case-head"><span>SELECTED WORK</span><span>2026 / 04</span></div>'+c.cases.map(x=>'<a class="skeg-case" href="#contact"><span>'+x[0]+'</span><div><small>'+x[2]+'</small><h2>'+x[1]+'</h2><p>'+x[3]+'</p></div><b>↗</b></a>').join('')+'</section><section class="skeg-notes variant-pad" id="studio"><p class="skeg-label">THE STUDIO</p><h2>'+c.noteTitle+'</h2><div>'+c.notes.map((x,i)=>'<article><span>0'+(i+1)+'</span><h3>'+x[0]+'</h3><p>'+x[1]+'</p></article>').join('')+'</div></section><section class="skeg-end variant-pad" id="contact"><p class="skeg-label">GET IN TOUCH</p><h2>'+c.contactTitle+'</h2><p>'+c.contactText+'</p><a href="mailto:'+c.contact+'">'+c.contact+' ↗</a></section></div>'}
function good(c){return '<div class="variant-page page-good">'+posterMarkup('good-tech')+'<div class="good-ticker"><span>'+c.ticker+'</span></div><section class="good-steps variant-pad" id="services">'+c.steps.map(x=>'<article><small>'+x[0]+'</small><div><span>'+x[1]+'</span><h2>'+x[2]+'</h2><p>'+x[3]+'</p></div><b>↗</b></article>').join('')+'</section><section class="good-proof variant-pad" id="work">'+c.proofs.map(x=>'<div><strong>'+x[0]+'</strong><span>'+x[1]+'</span></div>').join('')+'</section><section class="good-cta variant-pad" id="contact"><p>GOOD TECH / Z LAB</p><h2>'+c.cta+'</h2>'+link(c.button)+'</section></div>'}
function unitar(c){return '<div class="variant-page page-unitar">'+posterMarkup('unitar')+'<section class="unitar-modules variant-pad" id="work"><div class="unitar-module-head"><span>./MODULES</span><h2>BUILD<br />SOMETHING.</h2></div><div class="unitar-module-grid">'+c.modules.map(x=>'<article><small>'+x[0]+'</small><h3>'+x[1]+'</h3><p>'+x[2]+'</p><b>↗</b></article>').join('')+'</div></section><section class="unitar-log variant-pad" id="studio"><div><span>'+c.logTitle+'</span><h2>SHIP LOG</h2></div><ol>'+c.logs.map((x,i)=>'<li><b>0'+(i+1)+'</b><span>'+x+'</span><i>done</i></li>').join('')+'</ol></section><section class="unitar-command variant-pad" id="contact"><code><span>$</span> '+c.command+'<br /><b>output: project_ready</b></code><a href="mailto:'+mail+'">'+c.cta+' ↗</a></section></div>'}
function sodium(c){return '<div class="variant-page page-sodium">'+posterMarkup('sodium')+'<section class="sodium-index variant-pad" id="work"><div class="sodium-index-head"><span>THE CATALOGUE</span><span>05 TOOLS</span></div>'+c.products.map((x,i)=>'<a class="sodium-product" href="#contact"><span>'+x[0]+'</span><div><small>'+x[2]+'</small><h2>'+x[1]+'</h2><p>'+x[3]+'</p></div><b class="sodium-product-art art-'+i+'">'+(i+1)+'</b><em>↗</em></a>').join('')+'</section><section class="sodium-statement variant-pad" id="studio"><span>THE STUDIO</span><h2>'+c.statement+'</h2><div><b>Z LAB</b><p>Small software, made with care.</p></div></section><section class="sodium-contact variant-pad" id="contact"><h2>'+c.cta+'</h2><a href="mailto:'+mail+'">'+mail+' ↗</a></section></div>'}
function snow(c){return '<div class="variant-page page-snow">'+posterMarkup('snow')+'<div class="snow-marquee"><span>'+c.capabilities.join(' / ')+' / '+c.capabilities.join(' / ')+'</span></div><section class="snow-grid variant-pad" id="work"><div class="snow-grid-head"><span>SELECTED EXPERIENCES</span><h2>Made to be<br><em>remembered.</em></h2></div><div class="snow-cases">'+c.cases.map((x,i)=>'<a href="#contact" class="snow-case snow-case-'+i+'"><small>'+x[0]+'</small><h3>'+x[1]+'</h3><p>'+x[2]+'</p><b>↗</b></a>').join('')+'</div></section><section class="snow-process variant-pad" id="services"><p>OUR PROCESS</p><div>'+c.process.map((x,i)=>'<span><b>0'+(i+1)+'</b>'+x+'</span>').join('')+'</div></section><section class="snow-cta variant-pad" id="contact"><h2>'+c.cta+'</h2><a href="mailto:'+mail+'">'+mail+' ↗</a></section></div>'}
function market(c){return '<div class="variant-page page-market">'+posterMarkup('market')+'<section class="market-capabilities variant-pad" id="services"><div class="market-heading"><span>CAPABILITIES</span><h2>What we bring<br><em>to the table.</em></h2></div><div class="market-cap-list">'+c.capabilities.map((x,i)=>'<article><span>0'+(i+1)+'</span><h3>'+x[0]+'</h3><p>'+x[1]+'</p><b>↗</b></article>').join('')+'</div></section><section class="market-engage variant-pad" id="work"><p>HOW WE WORK</p><div>'+c.engage.map(x=>'<article><small>'+x[0]+'</small><h3>'+x[1]+'</h3><p>'+x[2]+'</p></article>').join('')+'</div></section><section class="market-cta variant-pad" id="contact"><p>LET’S BUILD THE NEXT VERSION</p><h2>'+c.ctaTitle+'</h2><span>'+c.ctaText+'</span><a href="mailto:'+mail+'">'+mail+' ↗</a></section></div>'}
function hermes(c){
 const emailHref='mailto:'+mail+'?subject='+encodeURIComponent(c.mailSubject)+'&amp;body='+encodeURIComponent(c.mailBody);
 return `<div class="variant-page page-hermes">
  <section class="hermes-hero" aria-labelledby="hermes-title">
   <div class="hermes-hero-grid">
    <div class="hermes-hero-copy">
     <p class="hermes-eyebrow"><span class="hermes-spark" aria-hidden="true">✳</span>${c.kicker}</p>
     <h1 id="hermes-title">${c.heroTitle}</h1>
     <p class="hermes-hero-lede">${c.heroText}</p>
     <div class="hermes-hero-actions"><a class="hermes-action hermes-action-primary" href="${emailHref}">${c.primary}<span aria-hidden="true">↗</span></a><a class="hermes-action hermes-action-secondary" href="#work">${c.secondary}<span aria-hidden="true">↓</span></a></div>
    </div>
    <div class="hermes-art" aria-hidden="true"><div class="hermes-rays"></div><div class="hermes-art-ring hermes-art-ring-outer"></div><div class="hermes-art-ring hermes-art-ring-inner"></div><span class="hermes-art-z">Z</span><span class="hermes-art-orbit">${c.heroOrbit}</span><span class="hermes-art-star">✳</span></div>
   </div>
   <div class="hermes-hero-rule"><span>${c.heroIndex}</span><span>Z LAB © 2026</span></div>
   <div class="hermes-brief"><div class="hermes-brief-heading"><p>${c.briefEyebrow}</p><h2>${c.briefTitle}</h2></div><div class="hermes-brief-items">${c.briefItems.map(x=>`<div><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}</div><a href="${emailHref}">${c.briefCta}<span aria-hidden="true">↗</span></a></div>
  </section>
  <section class="hermes-work hermes-section" id="work"><div class="hermes-section-head"><p class="hermes-section-label">${c.workEyebrow}</p><div><h2>${c.workTitle}</h2><p>${c.workIntro}</p></div></div><div class="hermes-path-grid">${c.paths.map(x=>`<article class="hermes-path-card"><span class="hermes-path-number">${x[0]}</span><div><p>${x[3]}</p><h3>${x[1]}</h3><span>${x[2]}</span></div></article>`).join('')}</div></section>
  <section class="hermes-services hermes-section" id="services"><div class="hermes-section-head"><p class="hermes-section-label">${c.servicesEyebrow}</p><div><h2>${c.servicesTitle}</h2><p>${c.servicesIntro}</p></div></div><div class="hermes-service-list">${c.services.map((x,i)=>`<div class="hermes-service-row"><span class="hermes-service-number">${String(i+1).padStart(2,'0')}</span><span class="hermes-service-category">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></section>
  <section class="hermes-studio hermes-section" id="studio"><div class="hermes-studio-intro"><p class="hermes-section-label">${c.studioEyebrow}</p><h2>${c.studioTitle}</h2><p>${c.studioIntro}</p><div class="hermes-studio-mark" aria-hidden="true">Z<span>LAB</span></div></div><div class="hermes-step-list">${c.steps.map(x=>`<article><small>${x[0]}</small><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}</div></section>
  <section class="hermes-faq hermes-section"><div><p class="hermes-section-label">${c.faqEyebrow}</p><h2>${c.faqTitle}</h2></div><div class="hermes-faq-list">${c.faqs.map(x=>`<details><summary>${x[0]}<span aria-hidden="true">+</span></summary><p>${x[1]}</p></details>`).join('')}</div></section>
  <section class="hermes-contact hermes-section" id="contact"><p class="hermes-section-label">${c.contactEyebrow}</p><h2>${c.contactTitle}</h2><div class="hermes-contact-bottom"><p>${c.contactIntro}</p><a class="hermes-action hermes-action-primary" href="${emailHref}">${c.contactCta}<span aria-hidden="true">↗</span></a></div></section>
 </div>`;
}
const renderers={unrushed,origin,skeg,'good-tech':good,unitar,sodium,'snow-fox':snow,market,hermes};
let observer;
function observeReveal(){if(observer)observer.disconnect();observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal,.variant-page [data-reveal]').forEach(el=>observer.observe(el))}
function applyStyle(next,resetScroll=true){style=next in renderers?next:'hermes';root.dataset.style=style;document.body.className='style-'+style;styleCurrent.textContent=styleNames[style];styleOptions.forEach(option=>option.classList.toggle('is-active',option.dataset.style===style));document.querySelector('.main-nav a[href="#work"]').textContent=style==='hermes'?(lang==='zh'?'项目方向':'Projects'):chrome[lang].navWork;main.innerHTML=renderers[style](pageCopy[styleKey[style]][lang]);main.querySelectorAll('[data-reveal]').forEach(el=>el.classList.add('reveal'));localStorage.setItem('zlab-style',style);observeReveal();bindDynamicEffects();if(resetScroll)window.scrollTo({top:0,behavior:'smooth'})}
function closeStylePanel(){stylePanel.hidden=true;styleToggle.setAttribute('aria-expanded','false')}
langToggle.addEventListener('click',()=>{lang=lang==='zh'?'en':'zh';renderChrome();applyStyle(style,false)});themeToggle.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('zlab-theme',root.dataset.theme)});styleToggle.addEventListener('click',()=>{const open=stylePanel.hidden;stylePanel.hidden=!open;styleToggle.setAttribute('aria-expanded',String(open))});styleOptions.forEach(option=>option.addEventListener('click',()=>{applyStyle(option.dataset.style);closeStylePanel()}));document.addEventListener('click',event=>{if(!event.target.closest('.style-picker'))closeStylePanel()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeStylePanel()});renderChrome();root.dataset.theme=localStorage.getItem('zlab-theme')||'dark';applyStyle(style,false);


function bindDynamicEffects(){
  document.querySelectorAll('.page-snow, .page-good, .poster-origin').forEach(page=>{
    const visual=page.matches('.poster-origin')?page:page.querySelector('.snow-orb, .good-hero-shape, .poster-snow-orbit, .poster-good-console');
    if(!visual)return;
    page.addEventListener('pointermove',event=>{
      const rect=page.getBoundingClientRect();
      const x=((event.clientX-rect.left)/rect.width-.5)*18;
      const y=((event.clientY-rect.top)/rect.height-.5)*18;
      visual.style.setProperty('--mx',x.toFixed(1)+'px');
      visual.style.setProperty('--my',y.toFixed(1)+'px');
    });
    page.addEventListener('pointerleave',()=>{visual.style.setProperty('--mx','0px');visual.style.setProperty('--my','0px')});
  });
}




